--------------------------------------------------------------------------------
-- FlyLo Booking · Initial schema
--
-- Catalog tables (airports, aircraft_types, cabins, seat_map_templates, meals,
-- routes) are reference data populated by the seed script.
--
-- Inventory tables (flights, flight_fares, flight_seats) are generated by the
-- seed script for the next 90 days from the catalog.
--
-- Transactional tables (bookings, booking_segments, passengers, seat_holds,
-- payments) are created empty.
--
-- Auth-aware tables (profiles) are tied to auth.users; we leave the column in
-- place but the v1 frontend does not use auth, so it is always nullable.
--------------------------------------------------------------------------------

create extension if not exists "pgcrypto";

--------------------------------------------------------------------------------
-- Catalog
--------------------------------------------------------------------------------

create table public.airports (
  iata          char(3) primary key,
  icao          char(4),
  city          text not null,
  country       text not null,
  continent     text not null check (
    continent in (
      'Africa', 'Asia', 'Europe',
      'North America', 'Oceania', 'South America'
    )
  ),
  lat           double precision not null,
  lon           double precision not null,
  tz            text not null,
  is_hub        boolean not null default false
);

create table public.aircraft_types (
  code            text primary key,
  model           text not null,
  seats           integer not null check (seats > 0),
  range_km        integer not null check (range_km > 0),
  cruise_kmh      integer not null check (cruise_kmh > 0),
  introduced_year integer,
  role            text not null check (role in ('short', 'long')),
  note            text
);

create table public.cabins (
  code        char(1) primary key,
  name        text not null,
  multiplier  numeric(4, 2) not null check (multiplier > 0),
  deck        text,
  dining      text,
  sort_order  integer not null default 0
);

create table public.seat_map_templates (
  aircraft_type   text not null references public.aircraft_types(code) on delete cascade,
  cabin           char(1) not null references public.cabins(code) on delete cascade,
  -- Authoritative geometry. Shape:
  --   { "rows": [ { "row": 1, "columns": ["A","D"], "zone": "Front suite", "price_eur": 85 }, ... ] }
  layout          jsonb not null,
  primary key (aircraft_type, cabin)
);

create table public.meals (
  id           text primary key,
  name         text not null,
  description  text not null,
  price_eur    integer not null default 0 check (price_eur >= 0),
  cabins       char(1)[] not null,
  sort_order   integer not null default 0
);

--------------------------------------------------------------------------------
-- Routes
--------------------------------------------------------------------------------

create table public.routes (
  id                  bigserial primary key,
  from_iata           char(3) not null references public.airports(iata),
  to_iata             char(3) not null references public.airports(iata) check (from_iata <> to_iata),
  duration_min        integer not null check (duration_min > 0),
  fare_from_eur       integer not null check (fare_from_eur > 0),
  freq_per_week       integer not null check (freq_per_week between 1 and 28),
  haul                text not null check (haul in ('short', 'long')),
  default_aircraft    text not null references public.aircraft_types(code),
  unique (from_iata, to_iata)
);

create index routes_from_idx on public.routes (from_iata);
create index routes_to_idx on public.routes (to_iata);

--------------------------------------------------------------------------------
-- Inventory (generated)
--------------------------------------------------------------------------------

create table public.flights (
  id              uuid primary key default gen_random_uuid(),
  flight_no       text not null,
  route_id        bigint not null references public.routes(id) on delete cascade,
  aircraft_type   text not null references public.aircraft_types(code),
  depart_at       timestamptz not null,
  arrive_at       timestamptz not null,
  duration_min    integer not null check (duration_min > 0),
  status          text not null default 'scheduled' check (
    status in ('scheduled', 'boarding', 'departed', 'arrived', 'cancelled')
  ),
  created_at      timestamptz not null default now(),
  unique (flight_no, depart_at)
);

create index flights_route_depart_idx on public.flights (route_id, depart_at);
create index flights_depart_idx on public.flights (depart_at);

create table public.flight_fares (
  flight_id       uuid not null references public.flights(id) on delete cascade,
  cabin           char(1) not null references public.cabins(code),
  base_eur        integer not null check (base_eur > 0),
  taxes_eur       integer not null default 0 check (taxes_eur >= 0),
  surface_eur     integer not null default 0 check (surface_eur >= 0),
  seats_total     integer not null check (seats_total >= 0),
  seats_available integer not null check (seats_available >= 0),
  primary key (flight_id, cabin)
);

create table public.flight_seats (
  flight_id   uuid not null references public.flights(id) on delete cascade,
  seat_id     text not null,
  cabin       char(1) not null references public.cabins(code),
  zone        text not null,
  price_eur   integer not null default 0 check (price_eur >= 0),
  status      text not null default 'available' check (
    status in ('available', 'held', 'taken', 'blocked')
  ),
  primary key (flight_id, seat_id)
);

create index flight_seats_cabin_status_idx on public.flight_seats (flight_id, cabin, status);

--------------------------------------------------------------------------------
-- Holds & bookings
--------------------------------------------------------------------------------

create table public.seat_holds (
  id          uuid primary key default gen_random_uuid(),
  flight_id   uuid not null references public.flights(id) on delete cascade,
  seat_id     text not null,
  session_id  uuid not null,
  booking_id  uuid,
  expires_at  timestamptz not null,
  created_at  timestamptz not null default now(),
  foreign key (flight_id, seat_id) references public.flight_seats(flight_id, seat_id) on delete cascade,
  unique (flight_id, seat_id)
);

create index seat_holds_expires_idx on public.seat_holds (expires_at);
create index seat_holds_session_idx on public.seat_holds (session_id);

create table public.bookings (
  pnr           char(6) primary key,
  session_id    uuid not null,
  user_id       uuid references auth.users(id) on delete set null,
  status        text not null default 'draft' check (
    status in ('draft', 'awaiting_payment', 'confirmed', 'cancelled')
  ),
  contact       jsonb not null default '{}'::jsonb,
  currency      char(3) not null default 'EUR',
  pax           integer not null check (pax between 1 and 9),
  base_eur      integer not null default 0,
  seats_eur     integer not null default 0,
  meals_eur     integer not null default 0,
  taxes_eur     integer not null default 0,
  surface_eur   integer not null default 0,
  total_eur     integer not null default 0,
  hold_expires_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  confirmed_at  timestamptz,
  cancelled_at  timestamptz
);

create index bookings_session_idx on public.bookings (session_id);
create index bookings_user_idx on public.bookings (user_id);
create index bookings_contact_email_idx on public.bookings ((lower(contact ->> 'email')));

create table public.booking_segments (
  id           bigserial primary key,
  booking_pnr  char(6) not null references public.bookings(pnr) on delete cascade,
  flight_id    uuid not null references public.flights(id),
  cabin        char(1) not null references public.cabins(code),
  segment_no   integer not null default 1,
  unique (booking_pnr, segment_no)
);

create table public.passengers (
  id            bigserial primary key,
  booking_pnr   char(6) not null references public.bookings(pnr) on delete cascade,
  passenger_no  integer not null,
  given_name    text not null,
  family_name   text not null,
  loyalty_no    text,
  notes         text,
  seat_id       text,
  meal_id       text references public.meals(id),
  unique (booking_pnr, passenger_no)
);

create table public.payments (
  id            uuid primary key default gen_random_uuid(),
  booking_pnr   char(6) not null references public.bookings(pnr) on delete cascade,
  provider      text not null default 'mock' check (provider in ('mock', 'stripe_test')),
  status        text not null default 'pending' check (
    status in ('pending', 'succeeded', 'failed', 'refunded')
  ),
  amount_eur    integer not null check (amount_eur >= 0),
  currency      char(3) not null default 'EUR',
  cardholder    text,
  card_last4    char(4),
  card_brand    text,
  created_at    timestamptz not null default now(),
  completed_at  timestamptz
);

create index payments_booking_idx on public.payments (booking_pnr);

--------------------------------------------------------------------------------
-- Profiles
--------------------------------------------------------------------------------

create table public.profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  home_iata    char(3) references public.airports(iata),
  loyalty_no   text,
  preferences  jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

--------------------------------------------------------------------------------
-- Update triggers
--------------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger bookings_set_updated_at
  before update on public.bookings
  for each row execute function public.set_updated_at();

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

--------------------------------------------------------------------------------
-- Row-Level Security
--
-- v1 frontend does not use auth; the backend service uses the service role
-- key (bypassing RLS). The policies below let any authenticated user read the
-- catalog and inventory, and own their own profile. The transactional tables
-- stay locked down — they are only ever touched through the backend service.
--------------------------------------------------------------------------------

alter table public.airports          enable row level security;
alter table public.aircraft_types    enable row level security;
alter table public.cabins            enable row level security;
alter table public.seat_map_templates enable row level security;
alter table public.meals             enable row level security;
alter table public.routes            enable row level security;
alter table public.flights           enable row level security;
alter table public.flight_fares      enable row level security;
alter table public.flight_seats      enable row level security;
alter table public.seat_holds        enable row level security;
alter table public.bookings          enable row level security;
alter table public.booking_segments  enable row level security;
alter table public.passengers        enable row level security;
alter table public.payments          enable row level security;
alter table public.profiles          enable row level security;

-- Public read on catalog + inventory (for future direct-from-browser reads)
create policy "catalog read" on public.airports          for select using (true);
create policy "catalog read" on public.aircraft_types    for select using (true);
create policy "catalog read" on public.cabins            for select using (true);
create policy "catalog read" on public.seat_map_templates for select using (true);
create policy "catalog read" on public.meals             for select using (true);
create policy "catalog read" on public.routes            for select using (true);
create policy "inventory read" on public.flights         for select using (true);
create policy "inventory read" on public.flight_fares    for select using (true);
create policy "inventory read" on public.flight_seats    for select using (true);

-- Profiles: owner only
create policy "profiles own select" on public.profiles for select using (auth.uid() = user_id);
create policy "profiles own upsert" on public.profiles for insert with check (auth.uid() = user_id);
create policy "profiles own update" on public.profiles for update using (auth.uid() = user_id);

-- Bookings + passengers + payments + holds: owner only (when logged in).
-- The backend service uses the service role key so these policies do not
-- block its writes; they protect the tables in case anything else ever talks
-- to the database directly.
create policy "bookings own select" on public.bookings
  for select using (auth.uid() is not null and auth.uid() = user_id);

create policy "passengers own select" on public.passengers
  for select using (
    auth.uid() is not null
    and exists (
      select 1 from public.bookings b
      where b.pnr = passengers.booking_pnr and b.user_id = auth.uid()
    )
  );

create policy "payments own select" on public.payments
  for select using (
    auth.uid() is not null
    and exists (
      select 1 from public.bookings b
      where b.pnr = payments.booking_pnr and b.user_id = auth.uid()
    )
  );

create policy "booking segments own select" on public.booking_segments
  for select using (
    auth.uid() is not null
    and exists (
      select 1 from public.bookings b
      where b.pnr = booking_segments.booking_pnr and b.user_id = auth.uid()
    )
  );
